os: linux
dist: xenial
language: python

stages:
  - test
  - deploy

install: pip install tox
script: tox

jobs:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - stage: deploy
      name: "Deploy to PyPI"
      python: 3.9
      install: pip install -U pip build
      script: python -m build
      deploy:
        provider: pypi
        distributions: "sdist bdist_wheel"
        username: __token__
        edge: true
        skip_existing: true
        on:
          python: 3.9
          tags: true
          branch: master
