name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        python-version:
          - '3.4'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
        exclude:
          - os: macos-latest
            python-version: '3.4'
          - os: windows-latest
            python-version: '3.4'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Python Version
      #   run: python --version
      - name: Install Dependencies
        run: python -m pip install -U pip tox
      - name: Test
        run: tox -e py,report
      - name: Coveralls
        # If pushed / is a pull request against main repo AND
        # we're running on Linux (this action only supports Linux)
        if:
          matrix.os == 'ubuntu-latest' && (
            (github.event_name == 'push' && github.repository == 'asyncon/setuptools-pipfile') ||
            github.event.pull_request.base.repo.full_name == 'asyncon/setuptools-pipfile'
          )
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          flag-name: py${{ matrix.python-version }}-${{ matrix.os }}

  finish:
    needs: test
    if:
      (github.event_name == 'push' && github.repository == 'asyncon/setuptools-pipfile') ||
      github.event.pull_request.base.repo.full_name == 'asyncon/setuptools-pipfile'
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
